// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavkrvlsieduqgjdahse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdmtydmxzaWVkdXFnamRhaHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODIyOTIsImV4cCI6MjA2Nzc1ODI5Mn0.Vyop3escuA4yeSmvZwrFyJldrFGgftVUjoTAwexeN-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});